### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by cclmyy** [lyz05/danmaku#4]
你好~在本地部署 运行npm install ，安装依赖后运行 node app.js报错，能帮忙解答下吗~多谢~

D:\Down\danmaku-main\danmaku-main\node_modules\leancloud-storage\dist\node\init.js:100
  if (!appId) throw new TypeError('appId must be a string');
              ^
TypeError: appId must be a string
    at Object.init (D:\Down\danmaku-main\danmaku-main\node_modules\leancloud-storage\dist\node\init.js:100:21)
    at Object.<anonymous> (D:\Down\danmaku-main\danmaku-main\utils\leancloud.js:7:4)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (D:\Down\danmaku-main\danmaku-main\routes\danmaku.js:14:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

**Comment by lyz05** [comment]
因为这是我线上部署的版本，还需要配置一些环境变量才能正常运行。
这些环境变量有服务器密钥等敏感信息，所以不能公开。
我会做一个不需要任何环境变量就能运行的本地版本，到时候跟着Readme中写的步骤运行就好。

**Comment by lyz05** [comment]
可以本地部署咯
